#!/usr/bin/env python3
"""
generate_images.py — fetch cover images from Pollinations Flux for a batch of
Develeap news articles and emit a manifest of decision objects.

Reads a JSON list of article records from --in (or stdin), writes JPEGs to
--out-dir using sha256(url)[:16].jpg as the filename when `url` is provided
(matches the Crawling-agent convention in scripts/test-image-gen.mjs), and
prints a JSON manifest to --manifest (or stdout) shaped per
references/output-contract.md.

This script is the Tier 4 (AI generation) producer only. Tiers 1-3 are decided
upstream by the skill; this script does not embed images into any surface.

Endpoint:
    GET https://image.pollinations.ai/prompt/{URL_ENCODED_PROMPT}
        ?width=1376&height=768&model=flux&seed={N}
        &nologo=true&private=true&enhance=false

Constraints:
- 16:9 (1376x768), Flux model only — see SKILL.md for why.
- Anonymous Pollinations is throttled to ~1 concurrent per IP. We pace at 3 s
  between requests and back off exponentially on 429.
- The STYLE_SUFFIX is locked here. Do NOT add color to it — color belongs in
  the per-article subject sentence (see references/composition-discipline.md).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import sys
import time
import urllib.parse
import urllib.request
import urllib.error
from pathlib import Path
from typing import Any

# Locked style suffix. Composition guards live here. Color does NOT.
# See references/composition-discipline.md before changing anything.
STYLE_SUFFIX = (
    "3D isometric illustration, centered composition, generous negative space, "
    "soft studio lighting, clean magazine editorial look, "
    "no text, no letters, no logos, no UI, no readable symbols, "
    "no people, no faces, sharp focus, single focal element"
)

ENDPOINT = "https://image.pollinations.ai/prompt/{prompt}"
WIDTH = 1376
HEIGHT = 768
MODEL = "flux"
INTER_REQUEST_DELAY_S = 3.0
MAX_RETRIES = 4
BACKOFF_BASE_S = 5.0
REQUEST_TIMEOUT_S = 90

LICENSE_NOTE = (
    "Generated by Pollinations.ai (Flux model). Develeap holds usage rights."
)


def sha16(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:16]


def stable_seed(article_id: str) -> int:
    # Deterministic per-article seed so reruns are idempotent until you bump it.
    return int(hashlib.sha256(article_id.encode("utf-8")).hexdigest()[:8], 16)


def build_prompt(subject: str) -> str:
    subject = subject.strip().rstrip(".")
    return f"{subject}, {STYLE_SUFFIX}"


def build_url(prompt: str, seed: int) -> str:
    encoded = urllib.parse.quote(prompt, safe="")
    qs = urllib.parse.urlencode({
        "width": WIDTH,
        "height": HEIGHT,
        "model": MODEL,
        "seed": seed,
        "nologo": "true",
        "private": "true",
        "enhance": "false",
    })
    return f"{ENDPOINT.format(prompt=encoded)}?{qs}"


def fetch_with_retry(url: str) -> bytes:
    last_err: Exception | None = None
    for attempt in range(MAX_RETRIES):
        try:
            req = urllib.request.Request(
                url,
                headers={"User-Agent": "develeap-news-imagery/1.0"},
            )
            with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT_S) as resp:
                data = resp.read()
                if not data:
                    raise RuntimeError("empty response body")
                return data
        except urllib.error.HTTPError as e:
            last_err = e
            if e.code == 429 or 500 <= e.code < 600:
                sleep_s = BACKOFF_BASE_S * (2 ** attempt) + random.uniform(0, 1)
                print(
                    f"  [retry] HTTP {e.code}; sleeping {sleep_s:.1f}s "
                    f"(attempt {attempt + 1}/{MAX_RETRIES})",
                    file=sys.stderr,
                )
                time.sleep(sleep_s)
                continue
            raise
        except (urllib.error.URLError, TimeoutError, RuntimeError) as e:
            last_err = e
            sleep_s = BACKOFF_BASE_S * (2 ** attempt) + random.uniform(0, 1)
            print(
                f"  [retry] {type(e).__name__}: {e}; sleeping {sleep_s:.1f}s "
                f"(attempt {attempt + 1}/{MAX_RETRIES})",
                file=sys.stderr,
            )
            time.sleep(sleep_s)
    raise RuntimeError(f"exhausted retries: {last_err}")


def article_filename(article: dict[str, Any]) -> tuple[str, str]:
    """Return (article_id, filename). Prefers url-derived sha16 filename."""
    if article.get("url"):
        return article["url"], f"{sha16(article['url'])}.jpg"
    if article.get("article_id"):
        return article["article_id"], f"{sha16(article['article_id'])}.jpg"
    raise ValueError("article needs `url` or `article_id`")


def make_decision(
    article: dict[str, Any],
    image_path: Path,
    prompt_used: str,
    status: str,
    error: str | None,
) -> dict[str, Any]:
    article_id, _ = article_filename(article)
    return {
        "article_id": article_id,
        "url": article.get("url"),
        "title": article.get("title"),
        "source": article.get("source"),
        "category": article.get("category"),
        "tags": article.get("tags", []),
        "status": status,
        "error": error,
        "decision": {
            "source_type": "ai_pollinations_flux",
            "image_url": None,
            "image_path": str(image_path) if status == "ok" else None,
            "image_hash": None,
            "prompt_used": prompt_used,
            "lead_color": article.get("lead_color"),
            "composition": article.get("composition", "isometric"),
            "license_note": LICENSE_NOTE,
            "attribution": None,
            "alt_text": article.get("alt_text"),
        },
        "rejected_sources": article.get("rejected_sources", []),
    }


def process(
    articles: list[dict[str, Any]],
    out_dir: Path,
    overwrite: bool,
) -> list[dict[str, Any]]:
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest: list[dict[str, Any]] = []

    if len(articles) > 50:
        print(
            f"[warn] {len(articles)} articles requested; expect "
            f"~{len(articles) * INTER_REQUEST_DELAY_S / 60:.0f}+ min wall time "
            "due to Pollinations rate limits.",
            file=sys.stderr,
        )

    for idx, article in enumerate(articles):
        try:
            article_id, filename = article_filename(article)
        except ValueError as e:
            manifest.append({
                "article_id": None,
                "status": "failed",
                "error": str(e),
                "decision": None,
            })
            continue

        subject = (article.get("subject") or "").strip()
        if not subject:
            manifest.append(make_decision(
                article, out_dir / filename, "",
                status="failed",
                error="missing `subject` — write one per prompt-recipes.md",
            ))
            continue

        path = out_dir / filename
        prompt = build_prompt(subject)

        if path.exists() and not overwrite:
            print(f"[{idx + 1}/{len(articles)}] cached: {filename}")
            manifest.append(make_decision(article, path, prompt, "ok", None))
            continue

        seed = article.get("seed") or stable_seed(article_id)
        url = build_url(prompt, seed)
        print(f"[{idx + 1}/{len(articles)}] fetching: {filename}")
        print(f"  subject: {subject}")

        try:
            bytes_ = fetch_with_retry(url)
            path.write_bytes(bytes_)
            kb = len(bytes_) / 1024
            print(f"  wrote {path} ({kb:.0f} KB)")
            manifest.append(make_decision(article, path, prompt, "ok", None))
        except Exception as e:  # noqa: BLE001
            print(f"  [fail] {e}", file=sys.stderr)
            manifest.append(make_decision(
                article, path, prompt, "failed", str(e),
            ))

        if idx < len(articles) - 1:
            time.sleep(INTER_REQUEST_DELAY_S)

    return manifest


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    p.add_argument(
        "--in", dest="in_path",
        help="Input JSON file (list of article records). Reads stdin if omitted.",
    )
    p.add_argument(
        "--out-dir", required=True,
        help="Directory to write JPEGs into (e.g. data/images/).",
    )
    p.add_argument(
        "--manifest",
        help="Write the decision manifest to this path. Prints to stdout if omitted.",
    )
    p.add_argument(
        "--overwrite", action="store_true",
        help="Re-fetch even when the destination file already exists.",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()

    if args.in_path:
        with open(args.in_path, encoding="utf-8") as f:
            articles = json.load(f)
    else:
        articles = json.load(sys.stdin)

    if not isinstance(articles, list):
        print("input must be a JSON array of article records", file=sys.stderr)
        return 2

    manifest = process(
        articles=articles,
        out_dir=Path(args.out_dir).resolve(),
        overwrite=args.overwrite,
    )

    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    if args.manifest:
        Path(args.manifest).write_text(payload + "\n", encoding="utf-8")
        print(f"[done] manifest written to {args.manifest}", file=sys.stderr)
    else:
        print(payload)

    failed = sum(1 for d in manifest if d.get("status") == "failed")
    if failed:
        print(f"[done] {failed}/{len(manifest)} failed", file=sys.stderr)
    return 1 if failed and failed == len(manifest) else 0


if __name__ == "__main__":
    sys.exit(main())
